name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
     
    - name: Restore NuGet Packages
      run: nuget restore TestConsole.sln
      
    - name: Build App
      run: msbuild TestConsole.sln
    
    - name: Run Tests
      run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:"TestConsoleTests\bin\Debug\TestConsoleTests"'
